import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

const PROPOSALS_DIR = path.resolve(__dirname, '../../../../qluu-data/proposals/Ready-for-COO');
const GRADER_SCRIPT = path.resolve(__dirname, 'red_team_grader.py');
const DUMMY_MUST_HAVES = JSON.stringify({ must_haves: [] }); // We only care about the integrity checks

console.log("==================================================");
console.log(" 🧹 LEGACY PROPOSAL SANITIZER (INTEGRITY SWEEP)");
console.log("==================================================\n");

if (!fs.existsSync(PROPOSALS_DIR)) {
    console.error(`❌ Data directory not found: ${PROPOSALS_DIR}`);
    process.exit(1);
}

const files = fs.readdirSync(PROPOSALS_DIR).filter(f => f.endsWith('.md'));
console.log(`> Found ${files.length} legacy proposals to scan against the forbidden claims blocklist.\n`);

let totalViolations = 0;
let cleanFiles = 0;
let dirtyFiles = 0;

const reportData: string[] = [];
reportData.push("# Legacy Proposal Sanitization Report\n");
reportData.push(`**Scan Date:** ${new Date().toISOString()}`);
reportData.push(`**Target Directory:** \`qluu-data/proposals/Ready-for-COO/\`\n`);

files.forEach(file => {
    const filePath = path.join(PROPOSALS_DIR, file);
    try {
        const output = execSync(`python "${GRADER_SCRIPT}" "${filePath}" '${DUMMY_MUST_HAVES}'`).toString().trim();
        const payload = JSON.parse(output);

        const integrityViolations = payload.deficiencies.filter((d: any) => 
            d.category === 'INTEGRITY VIOLATION' || d.category === 'TRL MISREPRESENTATION'
        );

        if (integrityViolations.length > 0) {
            dirtyFiles++;
            totalViolations += integrityViolations.length;
            reportData.push(`## ❌ ${file}\n`);
            console.log(`❌ FAIL: ${file} (${integrityViolations.length} violations)`);
            
            integrityViolations.forEach((v: any) => {
                reportData.push(`*   **[${v.severity}] ${v.category}**: ${v.error}`);
                console.log(`   └─ [${v.severity}] ${v.error}`);
            });
            reportData.push("\n");
        } else {
            cleanFiles++;
            console.log(`✅ PASS: ${file}`);
        }
    } catch (e: any) {
        console.error(`Error scanning ${file}: ${e.message}`);
    }
});

console.log("\n==================================================");
console.log(" 📊 SANITIZATION SUMMARY");
console.log("==================================================");
console.log(`Total Scanned:  ${files.length}`);
console.log(`Wait-Listed:    ${dirtyFiles} (Material Misrepresentations)`);
console.log(`Clean:          ${cleanFiles}`);
console.log(`Total Flags:    ${totalViolations}\n`);

if (dirtyFiles > 0) {
    const reportPath = path.join(PROPOSALS_DIR, 'SANITIZER_REPORT.md');
    reportData.unshift(`> [!CAUTION]\n> **${totalViolations} FRAUDULENT CLAIMS DETECTED**\n> These ${dirtyFiles} documents contain hallucinated credentials (fake TRL, fake ISO certs, fabricated deployments) generated by legacy models. They must NOT be submitted to any government portal.\n\n`);
    fs.writeFileSync(reportPath, reportData.join('\n'));
    console.log(`> 📝 Detailed report saved to: SANITIZER_REPORT.md`);
}
